#!/bin/bash

# creates a /dev/shm/{username}tmp folder and makes a symlink to it in your
# $HOME/etc/ directory. I use this to work on files which are encrypted on
# disk, in order to make sure that their plain-text versions do not persist.
if [ -e "/dev/shm" ]; then
  if [ ! -e "/dev/shm/$USER"'tmp' ]; then
    mkdir "/dev/shm/$USER"'tmp'
  fi

  if [ ! -e "$HOME/etc" ]; then
    mkdir "$HOME/etc"
  elif [ -d "$HOME/etc/tmp" ]; then
    rm -rf "$HOME/etc/tmp"
  fi

  ln -sTf "/dev/shm/$USER"'tmp' "$HOME/etc/tmp"
else
  echo "This script needs the '/dev/shm' device to work, but it was not found on this machine" 1>&2
fi
