#!/bin/bash

# This script will turn a file or directory into a tar ball, send it down the
# pipe to gpg2, which will then ask you for a passphrase for it and encrypt it

# did you pass an argument?

if [ ! -z "$1" ]; then

  # do you want to delete the original?
  destroy_original=false
  if [ "$1" == '--destroy-original' ]; then
    echo "original file will be destroyed"
    destroy_original=true 
    shift
  fi

  echo "origin: $1"
  echo "destination: $2"

  # did you provide a valid argument?
  if [ -e "$1" ]; then

    # did you provide a destination?
    if [ ! -z "$2" ]; then
      #echo "argument 2 exists: $2"

      # is the destination a directory?
      if [ -d "$2" ]; then
        # does your directory name end with a '/'
        dir=$(removeTrailingSlash $2)

        echo "this is dir $dir"
        filename="$(echo $(removeTrailingSlash "$1") | rev | cut -d'/' -f1 | rev).gpg"
        echo "this is filename $filename"

        echo "saving output file as $dir/$filename"
        tar czf - "$1" | gpg2 -c --output "$dir/$filename" - 
        
      else
        echo "$2 needs to be a directory you can write to." 1>&2
        exit 1
      fi
    else
      #echo "could not detect argument 2: $2"
      echo "this is 1 $1"
      filename="$(removeTrailingSlash $1).gpg"
      echo "this is filename $filename"
      echo "saving as '$filename'"
      tar czf - "$1" | gpg2 -c --output "$filename" - 
    fi

  else
    echo "You must specify a valid file or directory as your argument" 1>&2
    exit 1
  fi

  # did you actually want to destroy the original?
  if [[ "$destroy_original" == true && -e "$filename" ]]; then
    echo 'destoying original...'
    rm -rf "$1"
  fi

else
  echo "you must provide a file or directory as an argument" 1>&2
  exit 1
fi
