#!/bin/bash

# This script will turn a file or directory into a tar ball, send it down the
# pipe to gpg2, which will then ask you for a passphrase for it and encrypt it

# did you pass an argument?
if [ ! -z "$1" ]; then
  echo "$1"

  # do you want to delete the original?
  destroy_original=false
  if [ "$1" == '--destroy-original' ]; then
    echo "original file will be destroyed"
    destroy_original=true 
    shift
  fi


  # did you provide a valid argument?
  if [ -e $1 ]; then

    # did you provide a destination?
    if [ ! -z "$2" ]; then
      #echo "argument 2 exists: $2"

      # is the destination a directory?
      if [ -d "$2" ]; then
        # does your directory name end with a '/'
        dir=$2
        dirlength=${#dir}
        if [ ${dir:-1} == '/' ]; then
          dir=${dir:0:$dirlength-1}
        fi

        #echo "got to the tar -C: $2"
        echo "saving encrypted file at $2/$1"
        tar czf - $1 | gpg2 -c --output "$2/$1.gpg" - 

      else
        echo "$2 needs to be a directory you can write to." 1>&2
      fi
    else
      #echo "could not detect argument 2: $2"
      echo "saving in current directory"
      tar czf - $1 | gpg2 -c --output "$1.gpg" - 
    fi

  else
    echo "You must specify a valid file or directory as your argument" 1>&2
  fi

  # did you actually want to destroy the original?
  if [ "$destroy_original" == true ]; then
    echo 'destoying original...'
    rm -rf $1
  fi

else
  echo "you must provide a file or directory as an argument" 1>&2
fi
